### ISSUE TITLE
Customization service Error 

### ISSUE THREAD

**Issue by giulianodibacco** [music-encoding/customeization#11]
Error The customization process failed with an error INTERNAL SERVER ERROR

**Comment by bwbohl** [comment]
this might have been connected with https://github.com/music-encoding/music-encoding/issues/581

@giulianodibacco could you try again, please?

**Comment by paavomare** [comment]
I'm afraid that it still doesn't work. I've tried it with MEI CMN as well as a local customization file.

**Comment by bwbohl** [comment]
@kepper @ahankinson who of you has administrative access to http://customization.music-encoding.org?

**Comment by bwbohl** [comment]
Closed, because this service is deprecated and the repo has been archived.
