### ISSUE TITLE
unavailable / deprecated

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/customeization#13]
The service seems to be unavailable; am I right to consider the service deprecated?

A web lookup gives me the following:

IP address: 54.191.143.66

Location:
United States (US),
N/A
Region:
Oregon (5744337)
City:
Boardman
ZIP:
97818
Hostname:
ec2-54-191-143-66.us-west-2.compute.amazonaws.com → 54.191.143.66
IP range:
54.184.0.0 - 54.191.255.255
ISP:
Amazon.com
Organization:
Amazon.com
Blacklist:
No
TOR:
No
Zone:
America/Los_Angeles
Local:
Thu Jan 13 2022 02:59:03 GMT-0800 (PST)

@ahankinson and @kepper is there anything (server, vm,… )to be (1) taken down (or is it just a http vs https issue) and maybe we could (2) retarget the customisation.music-encoding.org to MEI Garage and (3) mark this repo as deprecated?

**Comment by ahankinson** [comment]
Yes, the service is suspended. It was run on McGill servers, but those have been moved.

I think forwarding the customization service to the MEI garage is the best course of action.

**Comment by kepper** [comment]
agreed, this should be redirected to the garage…

**Comment by bwbohl** [comment]
Closed, because this service is deprecated and the repo has been archived.
