### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/customeization#6]
Got the message "The customization process failed with an error INTERNAL SERVER ERROR."  Setting the verbose option on doesn't help find the problem.

**Comment by ahankinson** [comment]
Can you point to the problematic customization file so I can test it?

**Comment by bwbohl** [comment]
also see #11

**Comment by musicEnfanthen** [comment]
Closed, because this service is deprecated and the repo has been archived.
