### ISSUE TITLE
Validation error : value of attribute "meiversion" is invalid; must be equal to "2013"

### ISSUE THREAD

**Issue by marie-ototoi** [music-encoding/customeization#7]
When validating a document with attribute meiversion="3.0.0" (one of the official examples)
against RelaxNG schema (Latest stable / MEI all)

<img width="870" alt="capture d ecran 2016-08-24 a 10 07 22" src="https://cloud.githubusercontent.com/assets/1785024/17923429/6bc58964-69e4-11e6-8f11-bb1d35245423.png">

(I know the attribute is optional... just reporting...)

**Comment by ahankinson** [comment]
Thanks Marie, I've updated it so you should try again. It should work now.

**Comment by marie-ototoi** [comment]
I get these 2 errors (working with oxygen) 
The schema (same config : Latest stable / MEI all) only seems to contain statements about SVG elements 
<img width="867" alt="capture d ecran 2016-08-24 a 10 42 28" src="https://cloud.githubusercontent.com/assets/1785024/17924122/9da78312-69e7-11e6-92bc-cdfbdd2b96f2.png">
<img width="866" alt="capture d ecran 2016-08-24 a 10 42 30" src="https://cloud.githubusercontent.com/assets/1785024/17924123/9da98f9a-69e7-11e6-8343-4cb3bf0a2ad7.png">

**Comment by marie-ototoi** [comment]
fixed 👍
