### ISSUE TITLE
Erroneous install on http://custom.simssa.ca/?

### ISSUE THREAD

**Issue by frakel** [music-encoding/customeization#9]
Hi Andrew,

Since a few days the custumeization at http://custom.simssa.ca/ throws either an error or prevents the result from downloading. 

Today I got this message:

```
    Error The customization process failed with an error .  Please report this error and this message 
    at https://github.com/music-encoding/customeization. (status: error)
```

Thanks for caring about this. --franz

**Comment by ahankinson** [comment]
This should be fixed now.

**Comment by frakel** [comment]
again: `Error The customization process failed with an error Bad Gateway. Please report this error and this message at https://github.com/music-encoding/customeization. (status: error)`

Thanks for fixing this...

**Comment by ahankinson** [comment]
I have looked into this; it has to do with a change we made to the customization service to support the new modularization in MEI 4.0. I think I can fix it, but it might take a couple days.

If this is a problem, I would recommend you try installing the TEI stylesheets and running the transformation directly. There are some instructions for this in the README: https://github.com/music-encoding/music-encoding#building-mei-schemas

**Comment by frakel** [comment]
unfortunately the TEI Stylsheets tool does not run on my `centos-release-6-4.el6.centos.10.x86_64` due to an XSLT Processor mismatch throwing the following error:

`teianttasks.xml:386: java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl`

though this should be an issue of the CLASSPATH settings (at least to Michael Key's opinion;) which have to include the path to the `.../Stylesheets-dev/lib/saxon9he.jar` I was not able to fix this so long.

**Comment by ahankinson** [comment]
Do you have a typo in that command? It might be two dots (../Stylesheets) instead of three.

You can also provide an absolute path to the saxon file, e.g., 

`../Stylesheets-dev/bin/teitorelaxng --saxonjar=/home/username/Stylesheets-dev/lib/saxon9he.jar ... other commands`

If you run `../Stylesheets-dev/bin/teitorelaxng --help` what version of the stylesheets does it say you are running?

**Comment by frakel** [comment]
no, ... is no typo, but ellipsis,  just short for a longer path construct... 

it says `Stylesheet family version: 7.44.0a`

**Comment by ahankinson** [comment]
Yes, but it should be two and not three dots. Three dots does not work.

```
[user@machine directory]# ls .../
ls: cannot access .../: No such file or directory
```

**Comment by frakel** [comment]
yes of course, that's clear. As I said I just did not want to write the whole construct here , so I made the ellipsis, but without any path connotation ;)

And even with the --saxonjar option I get the same `java.lang.ClassNotFoundException`:

> teitorelaxng --saxonjar=lib/saxon9he.jar --localsource=../mei/source/driver.xml --odd myodds/mei-DME.odd

**Comment by frakel** [comment]
see follow-up of this discussion on https://github.com/TEIC/Stylesheets/issues/290
